# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/user/git/goxgui/goxgui/ui/main_window.ui'
#
# Created: Mon Jun  3 21:02:22 2013
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(906, 846)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.widgetMain = QtGui.QWidget(MainWindow)
        self.widgetMain.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetMain.sizePolicy().hasHeightForWidth())
        self.widgetMain.setSizePolicy(sizePolicy)
        self.widgetMain.setObjectName(_fromUtf8("widgetMain"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widgetMain)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tableInfo = QtGui.QTableView(self.widgetMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableInfo.sizePolicy().hasHeightForWidth())
        self.tableInfo.setSizePolicy(sizePolicy)
        self.tableInfo.setMaximumSize(QtCore.QSize(16777215, 42))
        self.tableInfo.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tableInfo.setFrameShadow(QtGui.QFrame.Plain)
        self.tableInfo.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableInfo.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableInfo.setAutoScroll(False)
        self.tableInfo.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableInfo.setTabKeyNavigation(False)
        self.tableInfo.setProperty("showDropIndicator", False)
        self.tableInfo.setAlternatingRowColors(False)
        self.tableInfo.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tableInfo.setShowGrid(True)
        self.tableInfo.setGridStyle(QtCore.Qt.DotLine)
        self.tableInfo.setWordWrap(False)
        self.tableInfo.setCornerButtonEnabled(False)
        self.tableInfo.setObjectName(_fromUtf8("tableInfo"))
        self.tableInfo.horizontalHeader().setVisible(False)
        self.tableInfo.verticalHeader().setVisible(False)
        self.tableInfo.verticalHeader().setDefaultSectionSize(20)
        self.tableInfo.verticalHeader().setMinimumSectionSize(20)
        self.verticalLayout_2.addWidget(self.tableInfo)
        self.tabTrading = QtGui.QTabWidget(self.widgetMain)
        self.tabTrading.setObjectName(_fromUtf8("tabTrading"))
        self.tabManual = QtGui.QWidget()
        self.tabManual.setObjectName(_fromUtf8("tabManual"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabManual)
        self.verticalLayout_3.setContentsMargins(12, -1, 12, 12)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.widget = QtGui.QWidget(self.tabManual)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(12)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.radioButtonBuy = QtGui.QRadioButton(self.widget)
        self.radioButtonBuy.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButtonBuy.setChecked(True)
        self.radioButtonBuy.setObjectName(_fromUtf8("radioButtonBuy"))
        self.horizontalLayout_4.addWidget(self.radioButtonBuy)
        self.radioButtonSell = QtGui.QRadioButton(self.widget)
        self.radioButtonSell.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButtonSell.setChecked(False)
        self.radioButtonSell.setObjectName(_fromUtf8("radioButtonSell"))
        self.horizontalLayout_4.addWidget(self.radioButtonSell)
        self.pushButtonSize = QtGui.QPushButton(self.widget)
        self.pushButtonSize.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonSize.setObjectName(_fromUtf8("pushButtonSize"))
        self.horizontalLayout_4.addWidget(self.pushButtonSize)
        self.doubleSpinBoxSize = QtGui.QDoubleSpinBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxSize.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxSize.setSizePolicy(sizePolicy)
        self.doubleSpinBoxSize.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.doubleSpinBoxSize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxSize.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBoxSize.setDecimals(8)
        self.doubleSpinBoxSize.setMaximum(999999999.0)
        self.doubleSpinBoxSize.setObjectName(_fromUtf8("doubleSpinBoxSize"))
        self.horizontalLayout_4.addWidget(self.doubleSpinBoxSize)
        self.pushButtonPrice = QtGui.QPushButton(self.widget)
        self.pushButtonPrice.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonPrice.setObjectName(_fromUtf8("pushButtonPrice"))
        self.horizontalLayout_4.addWidget(self.pushButtonPrice)
        self.doubleSpinBoxPrice = QtGui.QDoubleSpinBox(self.widget)
        self.doubleSpinBoxPrice.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxPrice.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxPrice.setSizePolicy(sizePolicy)
        self.doubleSpinBoxPrice.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.doubleSpinBoxPrice.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxPrice.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBoxPrice.setDecimals(5)
        self.doubleSpinBoxPrice.setMaximum(999999999.0)
        self.doubleSpinBoxPrice.setSingleStep(1.0)
        self.doubleSpinBoxPrice.setObjectName(_fromUtf8("doubleSpinBoxPrice"))
        self.horizontalLayout_4.addWidget(self.doubleSpinBoxPrice)
        self.pushButtonTotal = QtGui.QPushButton(self.widget)
        self.pushButtonTotal.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonTotal.setObjectName(_fromUtf8("pushButtonTotal"))
        self.horizontalLayout_4.addWidget(self.pushButtonTotal)
        self.doubleSpinBoxTotal = QtGui.QDoubleSpinBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxTotal.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxTotal.setSizePolicy(sizePolicy)
        self.doubleSpinBoxTotal.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.doubleSpinBoxTotal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxTotal.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBoxTotal.setDecimals(5)
        self.doubleSpinBoxTotal.setMaximum(999999999.0)
        self.doubleSpinBoxTotal.setSingleStep(1.0)
        self.doubleSpinBoxTotal.setObjectName(_fromUtf8("doubleSpinBoxTotal"))
        self.horizontalLayout_4.addWidget(self.doubleSpinBoxTotal)
        self.pushButtonGo = QtGui.QPushButton(self.widget)
        self.pushButtonGo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonGo.setToolTip(_fromUtf8(""))
        self.pushButtonGo.setObjectName(_fromUtf8("pushButtonGo"))
        self.horizontalLayout_4.addWidget(self.pushButtonGo)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(12)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.lineEditOrder = QtGui.QLineEdit(self.widget)
        self.lineEditOrder.setObjectName(_fromUtf8("lineEditOrder"))
        self.horizontalLayout_8.addWidget(self.lineEditOrder)
        self.pushButtonCancel = QtGui.QPushButton(self.widget)
        self.pushButtonCancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonCancel.setObjectName(_fromUtf8("pushButtonCancel"))
        self.horizontalLayout_8.addWidget(self.pushButtonCancel)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.verticalLayout_3.addWidget(self.widget)
        self.tabTrading.addTab(self.tabManual, _fromUtf8(""))
        self.tabAuto = QtGui.QWidget()
        self.tabAuto.setEnabled(False)
        self.tabAuto.setObjectName(_fromUtf8("tabAuto"))
        self.tabTrading.addTab(self.tabAuto, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabTrading)
        self.textBrowserStatus = QtGui.QTextBrowser(self.widgetMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowserStatus.sizePolicy().hasHeightForWidth())
        self.textBrowserStatus.setSizePolicy(sizePolicy)
        self.textBrowserStatus.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        self.textBrowserStatus.setFont(font)
        self.textBrowserStatus.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textBrowserStatus.setToolTip(_fromUtf8(""))
        self.textBrowserStatus.setFrameShape(QtGui.QFrame.WinPanel)
        self.textBrowserStatus.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textBrowserStatus.setOpenLinks(False)
        self.textBrowserStatus.setObjectName(_fromUtf8("textBrowserStatus"))
        self.verticalLayout_2.addWidget(self.textBrowserStatus)
        self.tabOrders = QtGui.QTabWidget(self.widgetMain)
        self.tabOrders.setObjectName(_fromUtf8("tabOrders"))
        self.tabBidAsk = QtGui.QWidget()
        self.tabBidAsk.setObjectName(_fromUtf8("tabBidAsk"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tabBidAsk)
        self.verticalLayout_5.setContentsMargins(12, -1, 12, 12)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.tableBid = QtGui.QTableView(self.tabBidAsk)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableBid.sizePolicy().hasHeightForWidth())
        self.tableBid.setSizePolicy(sizePolicy)
        self.tableBid.setMinimumSize(QtCore.QSize(420, 300))
        self.tableBid.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableBid.setFrameShape(QtGui.QFrame.WinPanel)
        self.tableBid.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableBid.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableBid.setProperty("showDropIndicator", False)
        self.tableBid.setAlternatingRowColors(True)
        self.tableBid.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tableBid.setGridStyle(QtCore.Qt.DotLine)
        self.tableBid.setWordWrap(False)
        self.tableBid.setCornerButtonEnabled(False)
        self.tableBid.setObjectName(_fromUtf8("tableBid"))
        self.tableBid.horizontalHeader().setCascadingSectionResizes(True)
        self.tableBid.horizontalHeader().setStretchLastSection(False)
        self.tableBid.verticalHeader().setVisible(False)
        self.tableBid.verticalHeader().setDefaultSectionSize(20)
        self.tableBid.verticalHeader().setMinimumSectionSize(20)
        self.horizontalLayout_3.addWidget(self.tableBid)
        self.tableAsk = QtGui.QTableView(self.tabBidAsk)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableAsk.sizePolicy().hasHeightForWidth())
        self.tableAsk.setSizePolicy(sizePolicy)
        self.tableAsk.setMinimumSize(QtCore.QSize(420, 300))
        self.tableAsk.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableAsk.setAutoFillBackground(True)
        self.tableAsk.setFrameShape(QtGui.QFrame.WinPanel)
        self.tableAsk.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableAsk.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableAsk.setProperty("showDropIndicator", False)
        self.tableAsk.setAlternatingRowColors(True)
        self.tableAsk.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tableAsk.setGridStyle(QtCore.Qt.DotLine)
        self.tableAsk.setWordWrap(False)
        self.tableAsk.setCornerButtonEnabled(False)
        self.tableAsk.setObjectName(_fromUtf8("tableAsk"))
        self.tableAsk.verticalHeader().setVisible(False)
        self.tableAsk.verticalHeader().setDefaultSectionSize(20)
        self.tableAsk.verticalHeader().setMinimumSectionSize(20)
        self.horizontalLayout_3.addWidget(self.tableAsk)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.tabOrders.addTab(self.tabBidAsk, _fromUtf8(""))
        self.tabUser = QtGui.QWidget()
        self.tabUser.setEnabled(False)
        self.tabUser.setObjectName(_fromUtf8("tabUser"))
        self.tabOrders.addTab(self.tabUser, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabOrders)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.checkBoxLogTicker = QtGui.QCheckBox(self.widgetMain)
        self.checkBoxLogTicker.setChecked(True)
        self.checkBoxLogTicker.setObjectName(_fromUtf8("checkBoxLogTicker"))
        self.verticalLayout_4.addWidget(self.checkBoxLogTicker)
        self.checkBoxLogSystem = QtGui.QCheckBox(self.widgetMain)
        self.checkBoxLogSystem.setChecked(True)
        self.checkBoxLogSystem.setObjectName(_fromUtf8("checkBoxLogSystem"))
        self.verticalLayout_4.addWidget(self.checkBoxLogSystem)
        self.checkBoxLogDepth = QtGui.QCheckBox(self.widgetMain)
        self.checkBoxLogDepth.setChecked(True)
        self.checkBoxLogDepth.setObjectName(_fromUtf8("checkBoxLogDepth"))
        self.verticalLayout_4.addWidget(self.checkBoxLogDepth)
        self.checkBoxLogTrade = QtGui.QCheckBox(self.widgetMain)
        self.checkBoxLogTrade.setChecked(True)
        self.checkBoxLogTrade.setObjectName(_fromUtf8("checkBoxLogTrade"))
        self.verticalLayout_4.addWidget(self.checkBoxLogTrade)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.textBrowserLog = QtGui.QTextBrowser(self.widgetMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowserLog.sizePolicy().hasHeightForWidth())
        self.textBrowserLog.setSizePolicy(sizePolicy)
        self.textBrowserLog.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        self.textBrowserLog.setFont(font)
        self.textBrowserLog.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textBrowserLog.setFrameShape(QtGui.QFrame.WinPanel)
        self.textBrowserLog.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textBrowserLog.setObjectName(_fromUtf8("textBrowserLog"))
        self.horizontalLayout.addWidget(self.textBrowserLog)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_2.setStretch(3, 1)
        MainWindow.setCentralWidget(self.widgetMain)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 906, 22))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuOptions = QtGui.QMenu(self.menuBar)
        self.menuOptions.setObjectName(_fromUtf8("menuOptions"))
        MainWindow.setMenuBar(self.menuBar)
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.actionPreferences_2 = QtGui.QAction(MainWindow)
        self.actionPreferences_2.setObjectName(_fromUtf8("actionPreferences_2"))
        self.menuOptions.addAction(self.actionPreferences_2)
        self.menuBar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        self.tabTrading.setCurrentIndex(0)
        self.tabOrders.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.doubleSpinBoxSize, self.doubleSpinBoxPrice)
        MainWindow.setTabOrder(self.doubleSpinBoxPrice, self.doubleSpinBoxTotal)
        MainWindow.setTabOrder(self.doubleSpinBoxTotal, self.lineEditOrder)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "goxgui", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonBuy.setText(QtGui.QApplication.translate("MainWindow", "Buy", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonSell.setText(QtGui.QApplication.translate("MainWindow", "Sell", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSize.setToolTip(QtGui.QApplication.translate("MainWindow", "Recalculate size", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSize.setText(QtGui.QApplication.translate("MainWindow", "Size", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBoxSize.setToolTip(QtGui.QApplication.translate("MainWindow", "Size", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonPrice.setToolTip(QtGui.QApplication.translate("MainWindow", "Suggest price", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonPrice.setText(QtGui.QApplication.translate("MainWindow", "Price", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBoxPrice.setToolTip(QtGui.QApplication.translate("MainWindow", "Price", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonTotal.setToolTip(QtGui.QApplication.translate("MainWindow", "Recalculate total trade worth", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonTotal.setText(QtGui.QApplication.translate("MainWindow", "Total", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBoxTotal.setToolTip(QtGui.QApplication.translate("MainWindow", "Total trade worth", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonGo.setText(QtGui.QApplication.translate("MainWindow", "Go!", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditOrder.setToolTip(QtGui.QApplication.translate("MainWindow", "Paste order ID here or click link above", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditOrder.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Order ID", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCancel.setToolTip(QtGui.QApplication.translate("MainWindow", "Cancels the order with the specified ID", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCancel.setText(QtGui.QApplication.translate("MainWindow", "Cancel Order", None, QtGui.QApplication.UnicodeUTF8))
        self.tabTrading.setTabText(self.tabTrading.indexOf(self.tabManual), QtGui.QApplication.translate("MainWindow", "Trading", None, QtGui.QApplication.UnicodeUTF8))
        self.tabTrading.setTabText(self.tabTrading.indexOf(self.tabAuto), QtGui.QApplication.translate("MainWindow", "Unused", None, QtGui.QApplication.UnicodeUTF8))
        self.tabOrders.setTabText(self.tabOrders.indexOf(self.tabBidAsk), QtGui.QApplication.translate("MainWindow", "Bids / Asks", None, QtGui.QApplication.UnicodeUTF8))
        self.tabOrders.setTabText(self.tabOrders.indexOf(self.tabUser), QtGui.QApplication.translate("MainWindow", "Unused", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxLogTicker.setText(QtGui.QApplication.translate("MainWindow", "Ticker", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxLogSystem.setText(QtGui.QApplication.translate("MainWindow", "Trade", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxLogDepth.setText(QtGui.QApplication.translate("MainWindow", "Depth", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxLogTrade.setText(QtGui.QApplication.translate("MainWindow", "System", None, QtGui.QApplication.UnicodeUTF8))
        self.textBrowserLog.setToolTip(QtGui.QApplication.translate("MainWindow", "Technical output", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOptions.setTitle(QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setText(QtGui.QApplication.translate("MainWindow", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences_2.setText(QtGui.QApplication.translate("MainWindow", "Preferences", None, QtGui.QApplication.UnicodeUTF8))

